  
# Xamarin.Android
# Build a Xamarin.Android app and Xamarin.UITest assembly.
# Add steps that test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: AndroidSigning@3
  inputs:
    apkFiles: '$(outputDirectory)'
    apksign: true
    apksignerKeystoreFile: 'myRelease.keystore'
    apksignerKeystorePassword: '$(APPCENTER_KEYSTORE_PASSWORD)'
    apksignerKeystoreAlias: '$(APPCENTER_KEY_ALIAS)'
    apksignerKeyPassword: '$(APPCENTER_KEY_PASSWORD)'
    zipalign: true
    zipalignFile: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(outputDirectory)'

- task: XamariniOS@2
    inputs:
      solutionFile: '**/*iOS.csproj'
      configuration: 'AppStore'
      packageApp: true