# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/ContestPark.Mobile.sln'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/ContestPark.Mobile.sln'
    feedsToUse: 'select'
- task: MSBuild@1
  inputs:
    solution: 'src/Mobile Apps/ContestPark.Mobile/ContestPark.Mobile.Android/ContestPark.Mobile.Android.csproj'
    msbuildArchitecture: 'x64'
    platform: 'AnyCPU'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '-t:SignAndroidPackage -p:AndroidPackageFormat=aab -p:Configuration=$(BuildConfiguration) /p:OutputPath=$(OutputDirectory)'
- task: AndroidSigning@3
  inputs:
    apkFiles: '$(OutputDirectory)/*.aab'
    apksignerKeystoreFile: 'myRelease.keystore'
    apksignerKeystorePassword: '$(KeyStorePassword)'
    apksignerKeystoreAlias: '$(KeyStoreAlias)'
    apksignerKeyPassword: '$(KeyStorePassword)'
    apksignerArguments: '--verbose --min-sdk-version=19'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(OutputDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'