version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo $REPOSITORY_NAME
      - echo $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd "src/Services/Identity/ContestPark.Identity.API"
      - docker build -t contestparkidentityapi:latest .
  build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker tag $REPOSITORY_NAME:latest $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
