version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  pre_build:
    commands:
      - echo Build started on `date`
      - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
      - echo docker is build finish...
      - echo Started container tag...
      - docker tag contestparkbalance.api:latest $REPOSITORY_URI/balance-api:$IMAGE_TAG
      - docker tag contestparkcategory.api:latest $REPOSITORY_URI/category-apiZ:$IMAGE_TAG
      - docker tag contestparkchat.api:latest $REPOSITORY_URI/chat-api:$IMAGE_TAG
      - docker tag contestparkduel.api:latest $REPOSITORY_URI/duel-api:$IMAGE_TAG
      - docker tag contestparkidentity.api:latest $REPOSITORY_URI/identity-api:$IMAGE_TAG
      - docker tag contestparkocelotapigw.api:latest $REPOSITORY_URI/ocelot-apigw:$IMAGE_TAG
      - docker tag contestparkpost.api:latest $REPOSITORY_URI/post-api:$IMAGE_TAG
  build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/balance-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/category-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/chat-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/duel-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/identity-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/ocelot-apigw:$IMAGE_TAG
      - docker push $REPOSITORY_URI/post-api:$IMAGE_TAG
      - echo Pushing end...
