version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  pre_build:
    commands:
      - echo Build started on `date`
      - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
      - echo docker is build finish...
      - echo Started container tag...
      - docker tag contestparkbalance.api:latest $REPOSITORY_URI/balance-api:$IMAGE_TAG
      - docker tag contestparkfollow.api:latest $REPOSITORY_URI/follow-api:$IMAGE_TAG
      - docker tag contestparkcategory.api:latest $REPOSITORY_URI/category-api:$IMAGE_TAG
      - docker tag contestparkchat.api:latest $REPOSITORY_URI/chat-api:$IMAGE_TAG
      - docker tag contestparkduel.api:latest $REPOSITORY_URI/duel-api:$IMAGE_TAG
      - docker tag contestparkidentity.api:latest $REPOSITORY_URI/identity-api:$IMAGE_TAG
      - docker tag contestparkocelotapigw.api:latest $REPOSITORY_URI/ocelot-apigw:$IMAGE_TAG
      - docker tag contestparkpost.api:latest $REPOSITORY_URI/post-api:$IMAGE_TAG
      - docker tag contestparkadmin.api:latest $REPOSITORY_URI/admin-api:$IMAGE_TAG
      - docker tag contestparkbackgroundtasks:latest $REPOSITORY_URI/backgroundtasks:$IMAGE_TAG
      - docker tag contestparksignalr.api:latest $REPOSITORY_URI/signalr-api:$IMAGE_TAG
      - docker tag contestparknotification.api:latest $REPOSITORY_URI/notification-api:$IMAGE_TAG
      - docker tag contestparkmission.api:latest $REPOSITORY_URI/mission-api:$IMAGE_TAG
  build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/balance-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/follow-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/category-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/chat-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/duel-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/identity-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/ocelot-apigw:$IMAGE_TAG
      - docker push $REPOSITORY_URI/post-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/admin-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/backgroundtasks:$IMAGE_TAG
      - docker push $REPOSITORY_URI/signalr-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/notification-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/mission-api:$IMAGE_TAG
      - echo Finish
      - printf '[{"name":"balance-api","imageUri":"%s"}]' $REPOSITORY_URI/balance-api:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"follow-api","imageUri":"%s"}]' $REPOSITORY_URI/follow-api:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"category-api","imageUri":"%s"}]' $REPOSITORY_URI/category-api:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"chat-api","imageUri":"%s"}]' $REPOSITORY_URI/chat-api:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"duel-api","imageUri":"%s"}]' $REPOSITORY_URI/duel-api:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"identity-api","imageUri":"%s"}]' $REPOSITORY_URI/identity-api:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"ocelot-api","imageUri":"%s"}]' $REPOSITORY_URI/ocelot-api:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"post-api","imageUri":"%s"}]' $REPOSITORY_URI/post-api:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"admin-api","imageUri":"%s"}]' $REPOSITORY_URI/admin-api:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"backgroundtasks-api","imageUri":"%s"}]' $REPOSITORY_URI/backgroundtasks-api:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"signalr-api","imageUri":"%s"}]' $REPOSITORY_URI/signalr-api:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"notification-api","imageUri":"%s"}]' $REPOSITORY_URI/notification-api:$IMAGE_TAG > imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json
