version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  pre_build:
    commands:
      - echo Build started on `date`
      - docker --version
      - cd "src/Services/Identity/ContestPark.Identity.API"
      - dir
      - docker build -t identity-api .
      - echo docker is build finish...
      - docker images
      - echo Started container tag...
      - docker tag balance-api:latest $REPOSITORY_URI/balance-api:$IMAGE_TAG
      - docker tag category-api:latest $REPOSITORY_URI/category-apiZ:$IMAGE_TAG
      - docker tag chat-api:latest $REPOSITORY_URI/chat-api:$IMAGE_TAG
      - docker tag duel-api:latest $REPOSITORY_URI/duel-api:$IMAGE_TAG
      - docker tag identity-api:latest $REPOSITORY_URI/identity-api:$IMAGE_TAG
      - docker tag ocelot-apigw:latest $REPOSITORY_URI/ocelot-apigw:$IMAGE_TAG
      - docker tag post-api:latest $REPOSITORY_URI/post-api:$IMAGE_TAG
  build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/balance-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/category-apiZ:$IMAGE_TAG
      - docker push $REPOSITORY_URI/chat-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/duel-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/identity-api:$IMAGE_TAG
      - docker push $REPOSITORY_URI/ocelot-apigw:$IMAGE_TAG
      - docker push $REPOSITORY_URI/post-api:$IMAGE_TAG
      - echo Pushing end...
