version: 0.2


phases:
  install:
    runtime-versions:
        docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker-compose --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=162939618331.dkr.ecr.eu-central-1.amazonaws.com/contestpark
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - cd /codebuild/output
      - echo klasörler
      - pwd
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $REPOSITORY_URI
      - pwd
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
files:
  - source: /codebuild/output/
    destination: /codebuild/output/
