version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd "src/Services/Identity/ContestPark.Identity.API"
      - echo file changed..
      - docker --version
      - pwd
      - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
      - echo docker is building...
      - docker tag $REPOSITORY_NAME:latest $REPOSITORY_URI:latest
  build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
