version: '3.4'

services:
  mysql-data:
    image: mysql:5.7
    volumes:
    - ./data:/var/lib/mysql
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine

  elasticsearch:
    build:
      context: ek/elasticsearch/
    volumes:
      - ./ek/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    build:
      context: ek/kibana/
    volumes:
      - ./ek/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  contestpark.identity.api:
    image: contestparkidentity.api:${TAG:-latest}
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: src/Services/Identity/ContestPark.Identity.API/Dockerfile

  contestpark.category.api:
    image: contestparkcategory.api:${TAG:-latest}
    depends_on:
      - rabbitmq
      - elasticsearch
    build:
      context: .
      dockerfile: src/Services/Category/ContestPark.Category.API/Dockerfile


  contestpark.follow.api:
    image: contestparkfollow.api:${TAG:-latest}
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: src/Services/Follow/ContestPark.Follow.API/Dockerfile
      

  contestpark.balance.api:
    image: contestparkbalance.api:${TAG:-latest}
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: src/Services/Balance/ContestPark.Balance.API/Dockerfile


  contestpark.ocelotapigw.api:
    image: contestparkocelotapigw.api:${TAG:-latest}
    depends_on:
      - contestpark.balance.api
      - contestpark.follow.api
      - contestpark.category.api
      - contestpark.identity.api
      - elasticsearch
      - mysql-data
    build:
      context: .
      dockerfile: src/ApiGateways/ContestPark.OcelotApiGw/Dockerfile
      

  contestpark.chat.api:
    image: contestparkchat.api:${TAG:-latest}
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: src/Services/Chat/ContestPark.Chat.API/Dockerfile

  contestpark.signalr.api:
    image: contestparksignalr.api:${TAG:-latest}
    depends_on:
      - rabbitmq
      - contestpark.chat.api
    build:
      context: .
      dockerfile: src/Services/Signalr/ContestPark.Signalr.API/Dockerfile
