version: '3.4'

services:
  mysql-data:
    image: mysql:5.7
    volumes:
    - ./data:/var/lib/mysql
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine

  contestpark.identity.api:
    image: contestparkidentity.api:${TAG:-latest}
    depends_on:
      - mysql-data
      - rabbitmq
    build:
      context: .
      dockerfile: src/Services/Identity/ContestPark.Identity.API/Dockerfile