version: '3.4'

services:
  contestpark.identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${CONTESTPARK_AZURE_IDENTITY_DB:-server=mysql-data;database=ContestPark;uid=root;pwd=root;}  
    ports:
      - "5101:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
