version: '3.4'

services:
  mysql-data:
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"    # Important: In a production environment your should remove the external port

  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  contestpark.identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${CONTESTPARK_AZURE_IDENTITY_DB:-server=mysql-data;uid=root;database=ContestPark.Identity;pwd=root;}
      - identityUrl=http://contestpark.identity.api
      - Audience=identity
      - SendGridApiKey=Test
      - EventBusConnection=${CONTESTPARK_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${CONTESTPARK_SERVICE_BUS_USERNAME}
      - EventBusPassword=${CONTESTPARK_SERVICE_BUS_PASSWORD}
      - AzureStoreAccountName=${CONTESTPARK_AZURE_STORE_ACCOUNT_NAME}
      - AzureStoreAccountKey=${CONTESTPARK_AZURE_STORE_ACCOUNT_KEY}
      - ApplicationInsights_InstrumentationKey=${CONTESTPARK_APPINSIGHTS_INSTRUMENTATIONKEY}
    ports:
      - "5103:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    
  contestpark.category.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - identityUrl=http://contestpark.identity.api
      - Audience=category
      - EventBusConnection=${CONTESTPARK_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${CONTESTPARK_SERVICE_BUS_USERNAME}
      - EventBusPassword=${CONTESTPARK_SERVICE_BUS_PASSWORD}
      - CosmosDbServiceEndpoint=${CONTESTPARK_COSMOSDB_SERVICE_ENDPOINT}
      - CosmosDbAuthKeyOrResourceToken=${CONTESTPARK_COSMOSDB_AUTH_KEY_OR_RESOURCE_TOKEN}
      - CosmosDbDatabaseId=ContestPark.Category
      - ElasticSearchURI=http://elasticsearch:9200
      - ElasticSearchIndexName=categorysearch
      - ApplicationInsights_InstrumentationKey=${CONTESTPARK_APPINSIGHTS_INSTRUMENTATIONKEY}
    ports:
      - "5101:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    
  contestpark.follow.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - identityUrl=http://contestpark.identity.api
      - Audience=follow
      - EventBusConnection=${CONTESTPARK_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${CONTESTPARK_SERVICE_BUS_USERNAME}
      - EventBusPassword=${CONTESTPARK_SERVICE_BUS_PASSWORD}
      - CosmosDbServiceEndpoint=${CONTESTPARK_COSMOSDB_SERVICE_ENDPOINT}
      - CosmosDbAuthKeyOrResourceToken=${CONTESTPARK_COSMOSDB_AUTH_KEY_OR_RESOURCE_TOKEN}
      - CosmosDbDatabaseId=ContestPark.Follow
      - ApplicationInsights_InstrumentationKey=${CONTESTPARK_APPINSIGHTS_INSTRUMENTATIONKEY}
    ports:
      - "5102:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro