version: "3.4"

services:
  contestpark.identity.api:
    image: contestparkidentity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/ContestPark.Identity.API/Dockerfile

  contestpark.category.api:
    image: contestparkcategory.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Category/ContestPark.Category.API/Dockerfile

  contestpark.follow.api:
    image: contestparkfollow.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Follow/ContestPark.Follow.API/Dockerfile

  contestpark.balance.api:
    image: contestparkbalance.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Balance/ContestPark.Balance.API/Dockerfile

  contestpark.ocelotapigw.api:
    image: contestparkocelotapigw.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ContestPark.OcelotApiGw/Dockerfile

  contestpark.chat.api:
    image: contestparkchat.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Chat/ContestPark.Chat.API/Dockerfile

  contestpark.signalr.api:
    image: contestparksignalr.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Signalr/ContestPark.Signalr.API/Dockerfile

  contestpark.post.api:
    image: contestparkpost.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Post/ContestPark.Post.API/Dockerfile

  contestpark.duel.api:
    image: contestparkduel.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Duel/ContestPark.Duel.API/Dockerfile
