//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestPark.Mobile.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestParkResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestParkResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContestPark.Mobile.AppResources.ContestParkResources", typeof(ContestParkResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İleri Düzeyde.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkmak istediğinize emin misiniz?.
        /// </summary>
        public static string AreYouSureYouWantToLeave {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakip Bekleniyor....
        /// </summary>
        public static string AwaitingOpponent {
            get {
                return ResourceManager.GetString("AwaitingOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acemi.
        /// </summary>
        public static string Beginner {
            get {
                return ResourceManager.GetString("Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahis.
        /// </summary>
        public static string Bet {
            get {
                return ResourceManager.GetString("Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Al.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategori kilitli. Kilidi açmak ister misiniz?.
        /// </summary>
        public static string CategoryLocked {
            get {
                return ResourceManager.GetString("CategoryLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Ara.
        /// </summary>
        public static string CategorySearch {
            get {
                return ResourceManager.GetString("CategorySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düello için sunucu ile bağlantı kurulamadı..
        /// </summary>
        public static string ConnectionToTheServerForTheDuelWasNotEstablished {
            get {
                return ResourceManager.GetString("ConnectionToTheServerForTheDuelWasNotEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategoriye ait geçmiş bulunmamakta..
        /// </summary>
        public static string ContestPostEmptyMessage {
            get {
                return ResourceManager.GetString("ContestPostEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Ücreti.
        /// </summary>
        public static string EntryFee {
            get {
                return ResourceManager.GetString("EntryFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış?.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzman.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAKİP BUL.
        /// </summary>
        public static string FindOpponent {
            get {
                return ResourceManager.GetString("FindOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip edenler.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi unuttum.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beleşçi.
        /// </summary>
        public static string Freeloader {
            get {
                return ResourceManager.GetString("Freeloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dahi.
        /// </summary>
        public static string Genius {
            get {
                return ResourceManager.GetString("Genius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzgünüz, beklenmedik bir hata oluştu. Lütfen tekrar deneyiniz.
        /// </summary>
        public static string GlobalErrorMessage {
            get {
                return ResourceManager.GetString("GlobalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifre yanlış..
        /// </summary>
        public static string invalid_username_or_password {
            get {
                return ResourceManager.GetString("invalid_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook ile giriş yap.
        /// </summary>
        public static string LoginWithFacebook {
            get {
                return ResourceManager.GetString("LoginWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usta.
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altın yok.
        /// </summary>
        public static string NoGold {
            get {
                return ResourceManager.GetString("NoGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çaylak.
        /// </summary>
        public static string Novice {
            get {
                return ResourceManager.GetString("Novice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyna.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödül.
        /// </summary>
        public static string Prize {
            get {
                return ResourceManager.GetString("Prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        public static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategorinin kilidini zaten açtınız..
        /// </summary>
        public static string ServerMessage_ThisCategoryOpen {
            get {
                return ResourceManager.GetString("ServerMessage_ThisCategoryOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilidi Aç.
        /// </summary>
        public static string UnLock {
            get {
                return ResourceManager.GetString("UnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategoriyi açmak için yeterli miktarda altınınız yok. Altın satın almak ister misiniz?.
        /// </summary>
        public static string YouDoNotHaveASufficientAmountOfGoldToOpenThisCategory {
            get {
                return ResourceManager.GetString("YouDoNotHaveASufficientAmountOfGoldToOpenThisCategory", resourceCulture);
            }
        }
    }
}
