//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestPark.Mobile.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestParkResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestParkResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContestPark.Mobile.AppResources.ContestParkResources", typeof(ContestParkResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertise watch, play games!.
        /// </summary>
        public static string AdvertiseWatchPlayGames {
            get {
                return ResourceManager.GetString("AdvertiseWatchPlayGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the prize-awarding process..
        /// </summary>
        public static string AnErrorOccurredDuringThePrizeAwardingProcess {
            get {
                return ResourceManager.GetString("AnErrorOccurredDuringThePrizeAwardingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to transfer your earnings to your account has been created..
        /// </summary>
        public static string ARequestToTransferYourEarningsToYourAccountHasBeenCreated {
            get {
                return ResourceManager.GetString("ARequestToTransferYourEarningsToYourAccountHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave?.
        /// </summary>
        public static string AreYouSureYouWantToLeave {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting opponent.
        /// </summary>
        public static string AwaitingOpponent {
            get {
                return ResourceManager.GetString("AwaitingOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance code.
        /// </summary>
        public static string BalanceCode {
            get {
                return ResourceManager.GetString("BalanceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        public static string Beginner {
            get {
                return ResourceManager.GetString("Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet.
        /// </summary>
        public static string Bet {
            get {
                return ResourceManager.GetString("Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking.
        /// </summary>
        public static string Blocking {
            get {
                return ResourceManager.GetString("Blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category is locked. Do you want to unlock?.
        /// </summary>
        public static string CategoryLocked {
            get {
                return ResourceManager.GetString("CategoryLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change cover picture.
        /// </summary>
        public static string ChangeCoverPicture {
            get {
                return ResourceManager.GetString("ChangeCoverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change profile picture.
        /// </summary>
        public static string ChangeProfilePicture {
            get {
                return ResourceManager.GetString("ChangeProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Settings.
        /// </summary>
        public static string ChatSettings {
            get {
                return ResourceManager.GetString("ChatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an action.
        /// </summary>
        public static string ChooseAnAction {
            get {
                return ResourceManager.GetString("ChooseAnAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from library.
        /// </summary>
        public static string ChooseFromLibrary {
            get {
                return ResourceManager.GetString("ChooseFromLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect with server for duel..
        /// </summary>
        public static string ConnectionToTheServerForTheDuelWasNotEstablished {
            get {
                return ResourceManager.GetString("ConnectionToTheServerForTheDuelWasNotEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContestPark, Knowledge Contest is fun, you should play too. Please write my user &quot;{0}&quot; to the reference when sign up..
        /// </summary>
        public static string ContestParkKnowledgeContestIsFunYouShoulPlayTooPleaseWriteMyUserToTheReferenceWhenSignUp {
            get {
                return ResourceManager.GetString("ContestParkKnowledgeContestIsFunYouShoulPlayTooPleaseWriteMyUserToTheReferenceWhe" +
                        "nSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no history for this category..
        /// </summary>
        public static string ContestPostEmptyMessage {
            get {
                return ResourceManager.GetString("ContestPostEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest Store.
        /// </summary>
        public static string ContestStore {
            get {
                return ResourceManager.GetString("ContestStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to cash.
        /// </summary>
        public static string ConvertToCash {
            get {
                return ResourceManager.GetString("ConvertToCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Conversation.
        /// </summary>
        public static string DeleteConversation {
            get {
                return ResourceManager.GetString("DeleteConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the conversation between you and {0}?.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete message?.
        /// </summary>
        public static string DeleteMessageTitle {
            get {
                return ResourceManager.GetString("DeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Entire Speech?.
        /// </summary>
        public static string DeleteThisEntireConversation {
            get {
                return ResourceManager.GetString("DeleteThisEntireConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duel.
        /// </summary>
        public static string Duel {
            get {
                return ResourceManager.GetString("Duel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn Coins.
        /// </summary>
        public static string EarnCoins {
            get {
                return ResourceManager.GetString("EarnCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail must be a maximum of 255 characters..
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail field is required..
        /// </summary>
        public static string EmailRequiredFields {
            get {
                return ResourceManager.GetString("EmailRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter balance code.
        /// </summary>
        public static string EnterBalanceCode {
            get {
                return ResourceManager.GetString("EnterBalanceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter reference code(optional).
        /// </summary>
        public static string EnterReferenceCode {
            get {
                return ResourceManager.GetString("EnterReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code from sms.
        /// </summary>
        public static string EnterTheCodeFromSms {
            get {
                return ResourceManager.GetString("EnterTheCodeFromSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTRY FEE.
        /// </summary>
        public static string EntryFee {
            get {
                return ResourceManager.GetString("EntryFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting duel. Please try again..
        /// </summary>
        public static string ErrorStartingDuelPleaseTryAgain {
            get {
                return ResourceManager.GetString("ErrorStartingDuelPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Opponent.
        /// </summary>
        public static string FindOpponent {
            get {
                return ResourceManager.GetString("FindOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINISH BONUS.
        /// </summary>
        public static string FinishBonus {
            get {
                return ResourceManager.GetString("FinishBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on social networks.
        /// </summary>
        public static string FollowUsOnSocialNetworks {
            get {
                return ResourceManager.GetString("FollowUsOnSocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address or username. You will receive an email with your account information..
        /// </summary>
        public static string ForgetYourPasswordText {
            get {
                return ResourceManager.GetString("ForgetYourPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free coins.
        /// </summary>
        public static string FreeCoins {
            get {
                return ResourceManager.GetString("FreeCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeloader.
        /// </summary>
        public static string Freeloader {
            get {
                return ResourceManager.GetString("Freeloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full name must be a maximum of 255 characters..
        /// </summary>
        public static string FullNameMaxLength {
            get {
                return ResourceManager.GetString("FullNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full name must be a minimum of 3 characters or more..
        /// </summary>
        public static string FullNameMinLength {
            get {
                return ResourceManager.GetString("FullNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name field is required..
        /// </summary>
        public static string FullNameRequiredFields {
            get {
                return ResourceManager.GetString("FullNameRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genius.
        /// </summary>
        public static string Genius {
            get {
                return ResourceManager.GetString("Genius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an unexpected error occurred. Please try again.
        /// </summary>
        public static string GlobalErrorMessage {
            get {
                return ResourceManager.GetString("GlobalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you delete your copy of this conversation, it cannot be undone..
        /// </summary>
        public static string IfYouDeleteTheCopyOfThisSpeechThatCanNotBeUndone {
            get {
                return ResourceManager.GetString("IfYouDeleteTheCopyOfThisSpeechThatCanNotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is incorrect..
        /// </summary>
        public static string invalid_username_or_password {
            get {
                return ResourceManager.GetString("invalid_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid product id..
        /// </summary>
        public static string InvalidProductId {
            get {
                return ResourceManager.GetString("InvalidProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite a friend, earn money.
        /// </summary>
        public static string InviteSaveMoney {
            get {
                return ResourceManager.GetString("InviteSaveMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose.
        /// </summary>
        public static string Lose {
            get {
                return ResourceManager.GetString("Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCH SCORE.
        /// </summary>
        public static string MatchScore {
            get {
                return ResourceManager.GetString("MatchScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership was successful. But the login failed. Please login from the login page..
        /// </summary>
        public static string MembershipWasSuccessfulButTheLoginFailedPleaseLoginFromTheLoginPage {
            get {
                return ResourceManager.GetString("MembershipWasSuccessfulButTheLoginFailedPleaseLoginFromTheLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message list is empty..
        /// </summary>
        public static string MessageYourListIsEmpty {
            get {
                return ResourceManager.GetString("MessageYourListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions.
        /// </summary>
        public static string Missions {
            get {
                return ResourceManager.GetString("Missions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Missions Coming Soon!.
        /// </summary>
        public static string NewMissionsComingSoon {
            get {
                return ResourceManager.GetString("NewMissionsComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Gold.
        /// </summary>
        public static string NoGold {
            get {
                return ResourceManager.GetString("NoGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your Internet connection..
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice.
        /// </summary>
        public static string Novice {
            get {
                return ResourceManager.GetString("Novice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be 32 characters maximum..
        /// </summary>
        public static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be a minimum of 8 characters and above..
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is required..
        /// </summary>
        public static string PasswordRequiredFields {
            get {
                return ResourceManager.GetString("PasswordRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access allowed.
        /// </summary>
        public static string PermissionsDenied {
            get {
                return ResourceManager.GetString("PermissionsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is necessary to fill the field..
        /// </summary>
        public static string PhoneNumberRequiredFields {
            get {
                return ResourceManager.GetString("PhoneNumberRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Settings.
        /// </summary>
        public static string PictureSettings {
            get {
                return ResourceManager.GetString("PictureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYING.
        /// </summary>
        public static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to likes.
        /// </summary>
        public static string PostLikes {
            get {
                return ResourceManager.GetString("PostLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Profile.
        /// </summary>
        public static string PrivateProfile {
            get {
                return ResourceManager.GetString("PrivateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIZE.
        /// </summary>
        public static string Prize {
            get {
                return ResourceManager.GetString("Prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice chunk of coins you have over here.
        /// </summary>
        public static string ProductGold1500Description {
            get {
                return ResourceManager.GetString("ProductGold1500Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1500 Coins.
        /// </summary>
        public static string ProductGold1500Name {
            get {
                return ResourceManager.GetString("ProductGold1500Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coins like a cartoon duck.
        /// </summary>
        public static string ProductGold20000Description {
            get {
                return ResourceManager.GetString("ProductGold20000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20000 Coins.
        /// </summary>
        public static string ProductGold20000Name {
            get {
                return ResourceManager.GetString("ProductGold20000Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small investment can go far!.
        /// </summary>
        public static string ProductGold250Description {
            get {
                return ResourceManager.GetString("ProductGold250Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 Coins.
        /// </summary>
        public static string ProductGold250Name {
            get {
                return ResourceManager.GetString("ProductGold250Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shake it, shale it like a wallet full of coins.
        /// </summary>
        public static string ProductGold7000Description {
            get {
                return ResourceManager.GetString("ProductGold7000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7000 Coins.
        /// </summary>
        public static string ProductGold7000Name {
            get {
                return ResourceManager.GetString("ProductGold7000Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ₺12.99 to your account.
        /// </summary>
        public static string ProductMoney12 {
            get {
                return ResourceManager.GetString("ProductMoney12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ₺19.99 to your account.
        /// </summary>
        public static string ProductMoney19 {
            get {
                return ResourceManager.GetString("ProductMoney19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ₺6.99 to your account.
        /// </summary>
        public static string ProductMoney6 {
            get {
                return ResourceManager.GetString("ProductMoney6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase failed. Gold could not be loaded to your account. Please email support@contestpark.com..
        /// </summary>
        public static string PurchaseFail {
            get {
                return ResourceManager.GetString("PurchaseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no one you follow. Go follow the one!.
        /// </summary>
        public static string RankFollowingNull {
            get {
                return ResourceManager.GetString("RankFollowingNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference code.
        /// </summary>
        public static string ReferenceCode {
            get {
                return ResourceManager.GetString("ReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove block.
        /// </summary>
        public static string RemoveBlock {
            get {
                return ResourceManager.GetString("RemoveBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the required fields..
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTS.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenge.
        /// </summary>
        public static string Revenge {
            get {
                return ResourceManager.GetString("Revenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right on.
        /// </summary>
        public static string RightOn {
            get {
                return ResourceManager.GetString("RightOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Players or categories.
        /// </summary>
        public static string SearchPlayersOrCategories {
            get {
                return ResourceManager.GetString("SearchPlayersOrCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all.
        /// </summary>
        public static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select process.
        /// </summary>
        public static string SelectProcess {
            get {
                return ResourceManager.GetString("SelectProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to Gain Account.
        /// </summary>
        public static string SendMoney {
            get {
                return ResourceManager.GetString("SendMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send password.
        /// </summary>
        public static string SendPassword {
            get {
                return ResourceManager.GetString("SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category has already been unlocked..
        /// </summary>
        public static string ServerMessage_ThisCategoryOpen {
            get {
                return ResourceManager.GetString("ServerMessage_ThisCategoryOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show image.
        /// </summary>
        public static string ShowImage {
            get {
                return ResourceManager.GetString("ShowImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the SMS code.
        /// </summary>
        public static string SmsCode {
            get {
                return ResourceManager.GetString("SmsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound effects.
        /// </summary>
        public static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo.
        /// </summary>
        public static string TakeAPhoto {
            get {
                return ResourceManager.GetString("TakeAPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful purchase. Your Gold uploaded to your account..
        /// </summary>
        public static string ThePurchaseIsSuccessfulYourGoldBasBeenUploadedToYourAccount {
            get {
                return ResourceManager.GetString("ThePurchaseIsSuccessfulYourGoldBasBeenUploadedToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category has never been competing before. You can take first place!.
        /// </summary>
        public static string ThisCategoryRankNull {
            get {
                return ResourceManager.GetString("ThisCategoryRankNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIE.
        /// </summary>
        public static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time left.
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL XP.
        /// </summary>
        public static string TotalXp {
            get {
                return ResourceManager.GetString("TotalXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSFER TO MY BANK ACCOUNT.
        /// </summary>
        public static string TransferToBankAccount {
            get {
                return ResourceManager.GetString("TransferToBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        public static string Turkey {
            get {
                return ResourceManager.GetString("Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish lira.
        /// </summary>
        public static string TurkishLira {
            get {
                return ResourceManager.GetString("TurkishLira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access product list..
        /// </summary>
        public static string UnableToAccessTheProductList {
            get {
                return ResourceManager.GetString("UnableToAccessTheProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to store..
        /// </summary>
        public static string UnableToConnectToTheStore {
            get {
                return ResourceManager.GetString("UnableToConnectToTheStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photos selected..
        /// </summary>
        public static string UnableToTakePhotos {
            get {
                return ResourceManager.GetString("UnableToTakePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        public static string UnFollow {
            get {
                return ResourceManager.GetString("UnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the lock.
        /// </summary>
        public static string UnLock {
            get {
                return ResourceManager.GetString("UnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successful!.
        /// </summary>
        public static string UpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username must be a maximum of 255 characters..
        /// </summary>
        public static string UserNameMaxLength {
            get {
                return ResourceManager.GetString("UserNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username must be at least 3 characters or more..
        /// </summary>
        public static string UserNameMinLength {
            get {
                return ResourceManager.GetString("UserNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required..
        /// </summary>
        public static string UserNameRequiredFields {
            get {
                return ResourceManager.GetString("UserNameRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VICTORIOUS.
        /// </summary>
        public static string Victorious {
            get {
                return ResourceManager.GetString("Victorious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VICTORY BONUS.
        /// </summary>
        public static string VictoryBonus {
            get {
                return ResourceManager.GetString("VictoryBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was.
        /// </summary>
        public static string Was {
            get {
                return ResourceManager.GetString("Was", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch ad, get coins!.
        /// </summary>
        public static string WatchAdGetCoins {
            get {
                return ResourceManager.GetString("WatchAdGetCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We encountered while deleting your message with problems. Please try again..
        /// </summary>
        public static string WeHadaProblemDeletingTheMessagePleaseTryAgain {
            get {
                return ResourceManager.GetString("WeHadaProblemDeletingTheMessagePleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsanlar sana ne diye hitap etsin?.
        /// </summary>
        public static string WhatShouldWeopleCallYou {
            get {
                return ResourceManager.GetString("WhatShouldWeopleCallYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your username?.
        /// </summary>
        public static string WhatYouGetYourUsername {
            get {
                return ResourceManager.GetString("WhatYouGetYourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning.
        /// </summary>
        public static string Winning {
            get {
                return ResourceManager.GetString("Winning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username or e-mail address..
        /// </summary>
        public static string WriteYourUserNameOrEmailAddress {
            get {
                return ResourceManager.GetString("WriteYourUserNameOrEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can remove the barriers.
        /// </summary>
        public static string YouCanRemoveTheBarriers {
            get {
                return ResourceManager.GetString("YouCanRemoveTheBarriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have an adequate amount of gold to open this category. Want to buy gold?.
        /// </summary>
        public static string YouDoNotHaveASufficientAmountOfGoldToOpenThisCategory {
            get {
                return ResourceManager.GetString("YouDoNotHaveASufficientAmountOfGoldToOpenThisCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough balance to play. You must install balance out store contest..
        /// </summary>
        public static string YouDontHaveEnoughBalanceToPlayYouMustUploadTheBalanceViaTheContestStore {
            get {
                return ResourceManager.GetString("YouDontHaveEnoughBalanceToPlayYouMustUploadTheBalanceViaTheContestStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough gold to play. You can buy gold through the Contest store..
        /// </summary>
        public static string YouDontHaveEnoughGoldToPlayYouCanBuyGoldFromTheContestStore {
            get {
                return ResourceManager.GetString("YouDontHaveEnoughGoldToPlayYouCanBuyGoldFromTheContestStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t seem to have blocked anyone!.
        /// </summary>
        public static string YouDontSeemToBeBlockingAnyone {
            get {
                return ResourceManager.GetString("YouDontSeemToBeBlockingAnyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid code..
        /// </summary>
        public static string YouHaveEnteredAnInvalidCode {
            get {
                return ResourceManager.GetString("YouHaveEnteredAnInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You left the game during the duel. You are defeated..
        /// </summary>
        public static string YouLeftTheGameDuringTheDuelYouAreDefeated {
            get {
                return ResourceManager.GetString("YouLeftTheGameDuringTheDuelYouAreDefeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU LOSE!.
        /// </summary>
        public static string YouLose {
            get {
                return ResourceManager.GetString("YouLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must earn a minimum of 100 turkish lira to withdraw your winnings..
        /// </summary>
        public static string YouMustearnAminimumOfToWithdrawYourwinnings {
            get {
                return ResourceManager.GetString("YouMustearnAminimumOfToWithdrawYourwinnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your balance has been loaded..
        /// </summary>
        public static string YourBalanceHasBeenLoaded {
            get {
                return ResourceManager.GetString("YourBalanceHasBeenLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information has been updated..
        /// </summary>
        public static string YourInformationHasBeenUpdated {
            get {
                return ResourceManager.GetString("YourInformationHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string YourLevel {
            get {
                return ResourceManager.GetString("YourLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated..
        /// </summary>
        public static string YourPasswordHasBeenUpdated {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone does not support in-app purchase..
        /// </summary>
        public static string YourPhoneDoesNotSupportInAppPurchases {
            get {
                return ResourceManager.GetString("YourPhoneDoesNotSupportInAppPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU WIN!.
        /// </summary>
        public static string YouWin {
            get {
                return ResourceManager.GetString("YouWin", resourceCulture);
            }
        }
    }
}
