//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestPark.Mobile.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestParkResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestParkResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContestPark.Mobile.AppResources.ContestParkResources", typeof(ContestParkResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Ayarları.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İleri Düzeyde.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Ayarları.
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkmak istediğinize emin misiniz?.
        /// </summary>
        public static string AreYouSureYouWantToLeave {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakip Bekleniyor....
        /// </summary>
        public static string AwaitingOpponent {
            get {
                return ResourceManager.GetString("AwaitingOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acemi.
        /// </summary>
        public static string Beginner {
            get {
                return ResourceManager.GetString("Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahis.
        /// </summary>
        public static string Bet {
            get {
                return ResourceManager.GetString("Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelle.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engellenenler.
        /// </summary>
        public static string Blocking {
            get {
                return ResourceManager.GetString("Blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Al.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategori kilitli. Kilidi açmak ister misiniz?.
        /// </summary>
        public static string CategoryLocked {
            get {
                return ResourceManager.GetString("CategoryLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat resmi değiştir.
        /// </summary>
        public static string ChangeCoverPicture {
            get {
                return ResourceManager.GetString("ChangeCoverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile resmi değiştir.
        /// </summary>
        public static string ChangeProfilePicture {
            get {
                return ResourceManager.GetString("ChangeProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajlar.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sohbet Ayarları.
        /// </summary>
        public static string ChatSettings {
            get {
                return ResourceManager.GetString("ChatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem seçiniz.
        /// </summary>
        public static string ChooseAnAction {
            get {
                return ResourceManager.GetString("ChooseAnAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery&apos;den seç.
        /// </summary>
        public static string ChooseFromLibrary {
            get {
                return ResourceManager.GetString("ChooseFromLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düello için sunucu ile bağlantı kurulamadı..
        /// </summary>
        public static string ConnectionToTheServerForTheDuelWasNotEstablished {
            get {
                return ResourceManager.GetString("ConnectionToTheServerForTheDuelWasNotEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategoriye ait geçmiş bulunmamakta..
        /// </summary>
        public static string ContestPostEmptyMessage {
            get {
                return ResourceManager.GetString("ContestPostEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest Store.
        /// </summary>
        public static string ContestStore {
            get {
                return ResourceManager.GetString("ContestStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konuşmayı sil.
        /// </summary>
        public static string DeleteConversation {
            get {
                return ResourceManager.GetString("DeleteConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ile aranızdaki sohbeti silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj sil?.
        /// </summary>
        public static string DeleteMessageTitle {
            get {
                return ResourceManager.GetString("DeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Konuşmanın Tamamını Sil?.
        /// </summary>
        public static string DeleteThisEntireConversation {
            get {
                return ResourceManager.GetString("DeleteThisEntireConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düello.
        /// </summary>
        public static string Duel {
            get {
                return ResourceManager.GetString("Duel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altın Kazan.
        /// </summary>
        public static string EarnCoins {
            get {
                return ResourceManager.GetString("EarnCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Güncelle.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta maksimum 255 karakter olmalıdır..
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta alanını doldurmak zorunludur..
        /// </summary>
        public static string EmailRequiredFields {
            get {
                return ResourceManager.GetString("EmailRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Ücreti.
        /// </summary>
        public static string EntryFee {
            get {
                return ResourceManager.GetString("EntryFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzman.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakip Bul.
        /// </summary>
        public static string FindOpponent {
            get {
                return ResourceManager.GetString("FindOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip Et.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip edenler.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip edilenler.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal ağlarda bizi takip edin.
        /// </summary>
        public static string FollowUsOnSocialNetworks {
            get {
                return ResourceManager.GetString("FollowUsOnSocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta adresi veya kullanıcı adınızı giriniz. Hesap bilgilerinizi içeren bir e-posta alacaksınız..
        /// </summary>
        public static string ForgetYourPasswordText {
            get {
                return ResourceManager.GetString("ForgetYourPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi unuttum.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ücretsiz Altın.
        /// </summary>
        public static string FreeCoins {
            get {
                return ResourceManager.GetString("FreeCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beleşçi.
        /// </summary>
        public static string Freeloader {
            get {
                return ResourceManager.GetString("Freeloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad soyad.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad maksimum 255 karakter olmalıdır..
        /// </summary>
        public static string FullNameMaxLength {
            get {
                return ResourceManager.GetString("FullNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad minimum 3 karakter ve üzeri olmalıdır..
        /// </summary>
        public static string FullNameMinLength {
            get {
                return ResourceManager.GetString("FullNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad alanını doldurmak zorunludur..
        /// </summary>
        public static string FullNameRequiredFields {
            get {
                return ResourceManager.GetString("FullNameRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dahi.
        /// </summary>
        public static string Genius {
            get {
                return ResourceManager.GetString("Genius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzgünüz, beklenmedik bir hata oluştu. Lütfen tekrar deneyiniz.
        /// </summary>
        public static string GlobalErrorMessage {
            get {
                return ResourceManager.GetString("GlobalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu konuşmanın sendeki kopyasını silersen, bu işlem geri alınamaz..
        /// </summary>
        public static string IfYouDeleteTheCopyOfThisSpeechThatCanNotBeUndone {
            get {
                return ResourceManager.GetString("IfYouDeleteTheCopyOfThisSpeechThatCanNotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifre yanlış..
        /// </summary>
        public static string invalid_username_or_password {
            get {
                return ResourceManager.GetString("invalid_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz ürün id..
        /// </summary>
        public static string InvalidProductId {
            get {
                return ResourceManager.GetString("InvalidProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beğeni.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaybetti.
        /// </summary>
        public static string Lose {
            get {
                return ResourceManager.GetString("Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usta.
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye olma işlemi başarılı oldu. Fakat giriş yapılamadı. Lütfen giriş yap sayfasından giriş yapınız..
        /// </summary>
        public static string MembershipWasSuccessfulButTheLoginFailedPleaseLoginFromTheLoginPage {
            get {
                return ResourceManager.GetString("MembershipWasSuccessfulButTheLoginFailedPleaseLoginFromTheLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj listeniz boş..
        /// </summary>
        public static string MessageYourListIsEmpty {
            get {
                return ResourceManager.GetString("MessageYourListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevler.
        /// </summary>
        public static string Missions {
            get {
                return ResourceManager.GetString("Missions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Görevler Yakında!.
        /// </summary>
        public static string NewMissionsComingSoon {
            get {
                return ResourceManager.GetString("NewMissionsComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altın yok.
        /// </summary>
        public static string NoGold {
            get {
                return ResourceManager.GetString("NoGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet bağlantınızı kontrol ediniz..
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirimler.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çaylak.
        /// </summary>
        public static string Novice {
            get {
                return ResourceManager.GetString("Novice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eski Şifre.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Değiştir.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz maksimum 32 karakter olmalıdır..
        /// </summary>
        public static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz minimum 8 karakter ve üzeri olmalıdır..
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre alanını doldurmak zorunludur..
        /// </summary>
        public static string PasswordRequiredFields {
            get {
                return ResourceManager.GetString("PasswordRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erişim izni yok.
        /// </summary>
        public static string PermissionsDenied {
            get {
                return ResourceManager.GetString("PermissionsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Ayarları.
        /// </summary>
        public static string PictureSettings {
            get {
                return ResourceManager.GetString("PictureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyna.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beğeniler.
        /// </summary>
        public static string PostLikes {
            get {
                return ResourceManager.GetString("PostLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Gizle.
        /// </summary>
        public static string PrivateProfile {
            get {
                return ResourceManager.GetString("PrivateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödül.
        /// </summary>
        public static string Prize {
            get {
                return ResourceManager.GetString("Prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın alma işlemi başarısız. Altınlarınız hesabınıza yüklenemedi. Lütfen support@contestpark.com adresine mail atın..
        /// </summary>
        public static string PurchaseFail {
            get {
                return ResourceManager.GetString("PurchaseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıra.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip ettiğin kimse yok. Git birilerini takip et!.
        /// </summary>
        public static string RankFollowingNull {
            get {
                return ResourceManager.GetString("RankFollowingNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelli kaldır.
        /// </summary>
        public static string RemoveBlock {
            get {
                return ResourceManager.GetString("RemoveBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerekli alanları doldurunuz..
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puan.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyuncu veya Kategori ara.
        /// </summary>
        public static string SearchPlayersOrCategories {
            get {
                return ResourceManager.GetString("SearchPlayersOrCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        public static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçiniz.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Seçiniz.
        /// </summary>
        public static string SelectProcess {
            get {
                return ResourceManager.GetString("SelectProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi gönder.
        /// </summary>
        public static string SendPassword {
            get {
                return ResourceManager.GetString("SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategorinin kilidini zaten açtınız..
        /// </summary>
        public static string ServerMessage_ThisCategoryOpen {
            get {
                return ResourceManager.GetString("ServerMessage_ThisCategoryOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylaş.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  g .
        /// </summary>
        public static string ShortDay {
            get {
                return ResourceManager.GetString("ShortDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  s .
        /// </summary>
        public static string ShortHour {
            get {
                return ResourceManager.GetString("ShortHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  d .
        /// </summary>
        public static string ShortMinute {
            get {
                return ResourceManager.GetString("ShortMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  s .
        /// </summary>
        public static string ShortSeconds {
            get {
                return ResourceManager.GetString("ShortSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resmi görüntüle.
        /// </summary>
        public static string ShowImage {
            get {
                return ResourceManager.GetString("ShowImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses Efeckleri.
        /// </summary>
        public static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf çek.
        /// </summary>
        public static string TakeAPhoto {
            get {
                return ResourceManager.GetString("TakeAPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın alma işlemi başarılı. Altınlarınız hesabınıza yüklendi..
        /// </summary>
        public static string ThePurchaseIsSuccessfulYourGoldBasBeenUploadedToYourAccount {
            get {
                return ResourceManager.GetString("ThePurchaseIsSuccessfulYourGoldBasBeenUploadedToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategoride daha önce yarışan olmamış. İlk sırayı sen kapabilirsin!.
        /// </summary>
        public static string ThisCategoryRankNull {
            get {
                return ResourceManager.GetString("ThisCategoryRankNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berabere.
        /// </summary>
        public static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan Süre.
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün listesine erişilemedi..
        /// </summary>
        public static string UnableToAccessTheProductList {
            get {
                return ResourceManager.GetString("UnableToAccessTheProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazaya bağlanılamadı..
        /// </summary>
        public static string UnableToConnectToTheStore {
            get {
                return ResourceManager.GetString("UnableToConnectToTheStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf seçilemedi..
        /// </summary>
        public static string UnableToTakePhotos {
            get {
                return ResourceManager.GetString("UnableToTakePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takibi Bırak.
        /// </summary>
        public static string UnFollow {
            get {
                return ResourceManager.GetString("UnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilidi Aç.
        /// </summary>
        public static string UnLock {
            get {
                return ResourceManager.GetString("UnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme Başarılı!.
        /// </summary>
        public static string UpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adınız maksimum 255 karakter olmalıdır..
        /// </summary>
        public static string UserNameMaxLength {
            get {
                return ResourceManager.GetString("UserNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adınız minimum 3 karakter ve üzeri olmalıdır..
        /// </summary>
        public static string UserNameMinLength {
            get {
                return ResourceManager.GetString("UserNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı alanını doldurmak zorunludur..
        /// </summary>
        public static string UserNameRequiredFields {
            get {
                return ResourceManager.GetString("UserNameRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklam izle, altın kazan!.
        /// </summary>
        public static string WatchAdGetCoins {
            get {
                return ResourceManager.GetString("WatchAdGetCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınızı silerken problemle karşılaştık. Lütfen tekrar deneyiniz..
        /// </summary>
        public static string WeHadaProblemDeletingTheMessagePleaseTryAgain {
            get {
                return ResourceManager.GetString("WeHadaProblemDeletingTheMessagePleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazanan.
        /// </summary>
        public static string Winning {
            get {
                return ResourceManager.GetString("Winning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya eposta adresi yazınız..
        /// </summary>
        public static string WriteYourUserNameOrEmailAddress {
            get {
                return ResourceManager.GetString("WriteYourUserNameOrEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategoriyi açmak için yeterli miktarda altınınız yok. Altın satın almak ister misiniz?.
        /// </summary>
        public static string YouDoNotHaveASufficientAmountOfGoldToOpenThisCategory {
            get {
                return ResourceManager.GetString("YouDoNotHaveASufficientAmountOfGoldToOpenThisCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oynamak için yeterli altınınız yok. Contest store üzerinden altın satın alabilirsiniz..
        /// </summary>
        public static string YouDontHaveEnoughGoldToPlayYouCanBuyGoldFromTheContestStore {
            get {
                return ResourceManager.GetString("YouDontHaveEnoughGoldToPlayYouCanBuyGoldFromTheContestStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimseyi engellemiş görünmüyorsun!.
        /// </summary>
        public static string YouDontSeemToBeBlockingAnyone {
            get {
                return ResourceManager.GetString("YouDontSeemToBeBlockingAnyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgileriniz güncellendi..
        /// </summary>
        public static string YourInformationHasBeenUpdated {
            get {
                return ResourceManager.GetString("YourInformationHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seviyen.
        /// </summary>
        public static string YourLevel {
            get {
                return ResourceManager.GetString("YourLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz güncellendi..
        /// </summary>
        public static string YourPasswordHasBeenUpdated {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonunuz uygulama içi satın almayı desteklemiyor..
        /// </summary>
        public static string YourPhoneDoesNotSupportInAppPurchases {
            get {
                return ResourceManager.GetString("YourPhoneDoesNotSupportInAppPurchases", resourceCulture);
            }
        }
    }
}
