//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestPark.Chat.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChatResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChatResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContestPark.Chat.API.Resources.ChatResource", typeof(ChatResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred, please try again..
        /// </summary>
        public static string AnUnexpectedErrorHasOccurredPleaseTryAgain {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorHasOccurredPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sending failed. Please try again..
        /// </summary>
        public static string MessageSendingFailedPleaseTryAgain {
            get {
                return ResourceManager.GetString("MessageSendingFailedPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are between you and block this user. You or he may have blocked you..
        /// </summary>
        public static string ThereAreBetweenYouAndBlockThisUser_YouOrHeMayHaveBlockedYou {
            get {
                return ResourceManager.GetString("ThereAreBetweenYouAndBlockThisUser.YouOrHeMayHaveBlockedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already blocked..
        /// </summary>
        public static string ThisIserIsAlreadyBlocked {
            get {
                return ResourceManager.GetString("ThisIserIsAlreadyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not send messages to yourself..
        /// </summary>
        public static string YouCanNotMendMessagesToYourself {
            get {
                return ResourceManager.GetString("YouCanNotMendMessagesToYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not blocked this user..
        /// </summary>
        public static string YouHaveNotBlockedThisUser {
            get {
                return ResourceManager.GetString("YouHaveNotBlockedThisUser", resourceCulture);
            }
        }
    }
}
