---
apiVersion: v1
kind: Service
metadata:
  name: ocelot-apigw
  labels:
    run: ocelot-apigw
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: ocelot-apigw
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: admin-api
  labels:
    run: admin-api
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: admin-api
  type: LoadBalancer
