apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identity-api
spec:
  selector:
    matchLabels:
      run: identity-api
  replicas: 1
  template:
    metadata:
      labels:
        run: identity-api
    spec:
      containers:
        - name: identity-api
          image: $(REPOSITORY_URI)/identity-api:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ConnectionString
              value: $(CONTESTPARK_MYSQL_CONNECTIONSTRING)
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: identityUrl
              value: "http://identity-api"
            - name: balanceUrl
              value: "http://balance-api"
            - name: ChatUrl
              value: "http://chat-api"
            - name: FollowUrl
              value: "http://follow-api"
            - name: Audience
              value: "identity"
            - name: SendGridApiKey
              value: "Test"
            - name: EventBusConnection
              value: $(CONTESTPARK_AZURE_SERVICE_BUS)
            - name: EventBusUserName
              value: $(CONTESTPARK_SERVICE_BUS_USERNAME)
            - name: EventBusPassword
              value: $(CONTESTPARK_SERVICE_BUS_PASSWORD)
            - name: AwsAccessKeyId
              value: $(CONTESTPARK_AWS_ACCESS_KEY_Id)
            - name: AwsSecretAccessKey
              value: $(CONTESTPARK_AWS_SECRET_ACCESS_KEY)
            - name: IsMigrateDatabase
              value: "false"
            - name: AwsLogGroupName
              value: $(CONTESTPARK_AWS_LOG_GROUP_NAME)
            - name: GiftMoneyAmount
              value: $(CONTESTPARK_GIFT_MONEY_AMOUNT)
            - name: ClouldFrontUrl
              value: $(CONTESTPARK_CLOUDFRONT_URL)
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: follow-api
spec:
  selector:
    matchLabels:
      run: follow-api
  replicas: 1
  template:
    metadata:
      labels:
        run: follow-api
    spec:
      containers:
        - name: follow-api
          image: $(REPOSITORY_URI)/follow-api:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ConnectionString
              value: $(CONTESTPARK_MYSQL_CONNECTIONSTRING)
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: identityUrl
              value: "http://identity-api"
            - name: Audience
              value: "follow"
            - name: EventBusConnection
              value: $(CONTESTPARK_AZURE_SERVICE_BUS)
            - name: EventBusUserName
              value: $(CONTESTPARK_SERVICE_BUS_USERNAME)
            - name: EventBusPassword
              value: $(CONTESTPARK_SERVICE_BUS_PASSWORD)
            - name: Redis
              value: $(CONTESTPARK_AZURE_REDIS_SIGNALR_DB)
            - name: AwsAccessKeyId
              value: $(CONTESTPARK_AWS_ACCESS_KEY_Id)
            - name: AwsSecretAccessKey
              value: $(CONTESTPARK_AWS_SECRET_ACCESS_KEY)
            - name: IsMigrateDatabase
              value: "false"
            - name: AwsLogGroupName
              value: $(CONTESTPARK_AWS_LOG_GROUP_NAME)
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ocelot-apigw
spec:
  selector:
    matchLabels:
      run: ocelot-apigw
  replicas: 1
  template:
    metadata:
      labels:
        run: ocelot-apigw
    spec:
      containers:
        - name: ocelot-apigw
          image: $(REPOSITORY_URI)/ocelot-apigw:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: balance-api
spec:
  selector:
    matchLabels:
      run: balance-api
  replicas: 1
  template:
    metadata:
      labels:
        run: balance-api
    spec:
      containers:
        - name: balance-api
          image: $(REPOSITORY_URI)/balance-api:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ConnectionString
              value: $(CONTESTPARK_MYSQL_CONNECTIONSTRING)
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: identityUrl
              value: "http://identity-api"
            - name: Audience
              value: "balance"
            - name: EventBusConnection
              value: $(CONTESTPARK_AZURE_SERVICE_BUS)
            - name: EventBusUserName
              value: $(CONTESTPARK_SERVICE_BUS_USERNAME)
            - name: EventBusPassword
              value: $(CONTESTPARK_SERVICE_BUS_PASSWORD)
            - name: IsMigrateDatabase
              value: "false"
            - name: AwsAccessKeyId
              value: $(CONTESTPARK_AWS_ACCESS_KEY_Id)
            - name: AwsSecretAccessKey
              value: $(CONTESTPARK_AWS_SECRET_ACCESS_KEY)
            - name: AwsLogGroupName
              value: $(CONTESTPARK_AWS_LOG_GROUP_NAME)
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: category-api
spec:
  selector:
    matchLabels:
      run: category-api
  replicas: 1
  template:
    metadata:
      labels:
        run: category-api
    spec:
      containers:
        - name: category-api
          image: $(REPOSITORY_URI)/category-api:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ConnectionString
              value: $(CONTESTPARK_MYSQL_CONNECTIONSTRING)
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: identityUrl
              value: "http://identity-api"
            - name: balanceUrl
              value: "http://balance-api"
            - name: Audience
              value: "category"
            - name: EventBusConnection
              value: $(CONTESTPARK_AZURE_SERVICE_BUS)
            - name: EventBusUserName
              value: $(CONTESTPARK_SERVICE_BUS_USERNAME)
            - name: EventBusPassword
              value: $(CONTESTPARK_SERVICE_BUS_PASSWORD)
            - name: IsMigrateDatabase
              value: "false"
            - name: AwsAccessKeyId
              value: $(CONTESTPARK_AWS_ACCESS_KEY_Id)
            - name: AwsSecretAccessKey
              value: $(CONTESTPARK_AWS_SECRET_ACCESS_KEY)
            - name: AwsLogGroupName
              value: $(CONTESTPARK_AWS_LOG_GROUP_NAME)
            - name: ElasticSearchURI
              value: $(CONTESTPARK_ELASTIC_SEARCH_URI)
            - name: ElasticSearchIndexName
              value: "categorysearch"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chat-api
spec:
  selector:
    matchLabels:
      run: chat-api
  replicas: 1
  template:
    metadata:
      labels:
        run: chat-api
    spec:
      containers:
        - name: chat-api
          image: $(REPOSITORY_URI)/chat-api:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ConnectionString
              value: $(CONTESTPARK_MYSQL_CONNECTIONSTRING)
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: identityUrl
              value: "http://identity-api"
            - name: Audience
              value: "chat"
            - name: Redis
              value: $(CONTESTPARK_AZURE_REDIS_SIGNALR_DB)
            - name: EventBusConnection
              value: $(CONTESTPARK_AZURE_SERVICE_BUS)
            - name: EventBusUserName
              value: $(CONTESTPARK_SERVICE_BUS_USERNAME)
            - name: EventBusPassword
              value: $(CONTESTPARK_SERVICE_BUS_PASSWORD)
            - name: IsMigrateDatabase
              value: "false"
            - name: AwsAccessKeyId
              value: $(CONTESTPARK_AWS_ACCESS_KEY_Id)
            - name: AwsSecretAccessKey
              value: $(CONTESTPARK_AWS_SECRET_ACCESS_KEY)
            - name: AwsLogGroupName
              value: $(CONTESTPARK_AWS_LOG_GROUP_NAME)
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: duel-api
spec:
  selector:
    matchLabels:
      run: duel-api
  replicas: 1
  template:
    metadata:
      labels:
        run: duel-api
    spec:
      containers:
        - name: duel-api
          image: $(REPOSITORY_URI)/duel-api:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ConnectionString
              value: $(CONTESTPARK_MYSQL_CONNECTIONSTRING)
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: identityUrl
              value: "http://identity-api"
            - name: FollowUrl
              value: "http://follow-api"
            - name: SubCategoryUrl
              value: "http://category-api"
            - name: balanceUrl
              value: "http://balance-api"
            - name: Audience
              value: "duel"
            - name: Redis
              value: $(CONTESTPARK_AZURE_REDIS_SIGNALR_DB)
            - name: EventBusConnection
              value: $(CONTESTPARK_AZURE_SERVICE_BUS)
            - name: EventBusUserName
              value: $(CONTESTPARK_SERVICE_BUS_USERNAME)
            - name: EventBusPassword
              value: $(CONTESTPARK_SERVICE_BUS_PASSWORD)
            - name: IsMigrateDatabase
              value: "false"
            - name: AwsAccessKeyId
              value: $(CONTESTPARK_AWS_ACCESS_KEY_Id)
            - name: AwsSecretAccessKey
              value: $(CONTESTPARK_AWS_SECRET_ACCESS_KEY)
            - name: AwsLogGroupName
              value: $(CONTESTPARK_AWS_LOG_GROUP_NAME)
            - name: BetCommission
              value: "10"
            - name: ClouldFrontUrl
              value: $(CONTESTPARK_CLOUDFRONT_URL)

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: post-api
spec:
  selector:
    matchLabels:
      run: post-api
  replicas: 1
  template:
    metadata:
      labels:
        run: post-api
    spec:
      containers:
        - name: post-api
          image: $(REPOSITORY_URI)/post-api:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ConnectionString
              value: $(CONTESTPARK_MYSQL_CONNECTIONSTRING)
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: identityUrl
              value: "http://identity-api"
            - name: Audience
              value: "post"
            - name: Redis
              value: $(CONTESTPARK_AZURE_REDIS_SIGNALR_DB)
            - name: EventBusConnection
              value: $(CONTESTPARK_AZURE_SERVICE_BUS)
            - name: EventBusUserName
              value: $(CONTESTPARK_SERVICE_BUS_USERNAME)
            - name: EventBusPassword
              value: $(CONTESTPARK_SERVICE_BUS_PASSWORD)
            - name: IsMigrateDatabase
              value: "false"
            - name: AwsAccessKeyId
              value: $(CONTESTPARK_AWS_ACCESS_KEY_Id)
            - name: AwsSecretAccessKey
              value: $(CONTESTPARK_AWS_SECRET_ACCESS_KEY)
            - name: AwsLogGroupName
              value: $(CONTESTPARK_AWS_LOG_GROUP_NAME)

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-api
spec:
  selector:
    matchLabels:
      run: admin-api
  replicas: 1
  template:
    metadata:
      labels:
        run: admin-api
    spec:
      containers:
        - name: admin-api
          image: $(REPOSITORY_URI)/admin-api:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: identityUrl
              value: "http://identity-api"
            - name: ClouldFrontUrl
              value: $(CONTESTPARK_CLOUDFRONT_URL)
            - name: ConnectionString
              value: $(CONTESTPARK_MYSQL_CONNECTIONSTRING)
            - name: Audience
              value: "admin"
            - name: EventBusConnection
              value: $(CONTESTPARK_AZURE_SERVICE_BUS)
            - name: EventBusUserName
              value: $(CONTESTPARK_SERVICE_BUS_USERNAME)
            - name: EventBusPassword
              value: $(CONTESTPARK_SERVICE_BUS_PASSWORD)
            - name: AwsAccessKeyId
              value: $(CONTESTPARK_AWS_ACCESS_KEY_Id)
            - name: AwsSecretAccessKey
              value: $(CONTESTPARK_AWS_SECRET_ACCESS_KEY)
            - name: AwsLogGroupName
              value: $(CONTESTPARK_AWS_LOG_GROUP_NAME)
            - name: SpotifyClientId
              value: $(CONTESTPARK_SPOTIFY_CLIENTID)
            - name: SpotifySecretId
              value: $(CONTESTPARK_SPOTIFY_SECRETID)

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backgroundtasks
spec:
  selector:
    matchLabels:
      run: backgroundtasks
  replicas: 1
  template:
    metadata:
      labels:
        run: backgroundtasks
    spec:
      containers:
        - name: backgroundtasks
          image: $(REPOSITORY_URI)/backgroundtasks:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: EventBusConnection
              value: $(CONTESTPARK_AZURE_SERVICE_BUS)
            - name: EventBusUserName
              value: $(CONTESTPARK_SERVICE_BUS_USERNAME)
            - name: EventBusPassword
              value: $(CONTESTPARK_SERVICE_BUS_PASSWORD)
            - name: AwsAccessKeyId
              value: $(CONTESTPARK_AWS_ACCESS_KEY_Id)
            - name: AwsSecretAccessKey
              value: $(CONTESTPARK_AWS_SECRET_ACCESS_KEY)
            - name: AwsLogGroupName
              value: $(CONTESTPARK_AWS_LOG_GROUP_NAME)
            - name: DuelUrl
              value:  "http://duel-api"
              
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: signalr-api
spec:
  selector:
    matchLabels:
      run: signalr-api
  replicas: 1
  template:
    metadata:
      labels:
        run: signalr-api
    spec:
      containers:
        - name: signalr-api
          image: $(REPOSITORY_URI)/signalr-api:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: identityUrl
              value: "http://identity-api"
            - name: Audience
              value: "signalr"
            - name: EventBusConnection
              value: $(CONTESTPARK_AZURE_SERVICE_BUS)
            - name: EventBusUserName
              value: $(CONTESTPARK_SERVICE_BUS_USERNAME)
            - name: EventBusPassword
              value: $(CONTESTPARK_SERVICE_BUS_PASSWORD)
            - name: Redis
              value: $(CONTESTPARK_AZURE_REDIS_SIGNALR_DB)
            - name: AwsAccessKeyId
              value: $(CONTESTPARK_AWS_ACCESS_KEY_Id)
            - name: AwsSecretAccessKey
              value: $(CONTESTPARK_AWS_SECRET_ACCESS_KEY)
            - name: AwsLogGroupName
              value: $(CONTESTPARK_AWS_LOG_GROUP_NAME)

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notification-api
spec:
  selector:
    matchLabels:
      run: notification-api
  replicas: 1
  template:
    metadata:
      labels:
        run: notification-api
    spec:
      containers:
        - name: notification-api
          image: $(REPOSITORY_URI)/notification-api:$(IMAGE_TAG)
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionString
              value: $(CONTESTPARK_MYSQL_CONNECTIONSTRING)
            - name: identityUrl
              value: "http://identity-api"
            - name: Audience
              value: "notification"
            - name: EventBusConnection
              value: $(CONTESTPARK_AZURE_SERVICE_BUS)
            - name: EventBusUserName
              value: $(CONTESTPARK_SERVICE_BUS_USERNAME)
            - name: EventBusPassword
              value: $(CONTESTPARK_SERVICE_BUS_PASSWORD)
            - name: AwsAccessKeyId
              value: $(CONTESTPARK_AWS_ACCESS_KEY_Id)
            - name: AwsSecretAccessKey
              value: $(CONTESTPARK_AWS_SECRET_ACCESS_KEY)
            - name: AwsLogGroupName
              value: $(CONTESTPARK_AWS_LOG_GROUP_NAME)