//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestPark.Category.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContestPark.Category.API.Resources.CategoryResource", typeof(CategoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred from the system. Please try again..
        /// </summary>
        public static string AnErrorHasOccurredFromTheSystemPleaseTryAgain {
            get {
                return ResourceManager.GetString("AnErrorHasOccurredFromTheSystemPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open subcategory lock..
        /// </summary>
        public static string CouldNotPpenSubcategoryLock {
            get {
                return ResourceManager.GetString("CouldNotPpenSubcategoryLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followed categories.
        /// </summary>
        public static string FollowedCategories {
            get {
                return ResourceManager.GetString("FollowedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended categories.
        /// </summary>
        public static string RecommendedSubcategories {
            get {
                return ResourceManager.GetString("RecommendedSubcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last categories I played..
        /// </summary>
        public static string TheLastCategoriesIPlayed {
            get {
                return ResourceManager.GetString("TheLastCategoriesIPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category is already unlocked..
        /// </summary>
        public static string ThisCategoryIsAlreadyUnlocked {
            get {
                return ResourceManager.GetString("ThisCategoryIsAlreadyUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to follow this category, you need to unlock it..
        /// </summary>
        public static string ToBeAbleToFollowThisCategoryYouNeedToUnlockIt {
            get {
                return ResourceManager.GetString("ToBeAbleToFollowThisCategoryYouNeedToUnlockIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already following this category..
        /// </summary>
        public static string YouAreAlreadyFollowingThisCategory {
            get {
                return ResourceManager.GetString("YouAreAlreadyFollowingThisCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not unlock the Free category..
        /// </summary>
        public static string YouCanNotUnlockTheFreeCategory {
            get {
                return ResourceManager.GetString("YouCanNotUnlockTheFreeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must follow this category to deactivate the category..
        /// </summary>
        public static string YouMustFollowThisCategoryToDeactivateTheCategory {
            get {
                return ResourceManager.GetString("YouMustFollowThisCategoryToDeactivateTheCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your balance is insufficient..
        /// </summary>
        public static string YourBalanceIsInsufficient {
            get {
                return ResourceManager.GetString("YourBalanceIsInsufficient", resourceCulture);
            }
        }
    }
}
