//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestPark.Identity.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContestPark.Identity.API.Resources.IdentityResource", typeof(IdentityResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address is not correct fotmat..
        /// </summary>
        public static string EmailFormating {
            get {
                return ResourceManager.GetString("EmailFormating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email should be a maximum of 255 characters..
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address required field..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code below to refresh the password:.
        /// </summary>
        public static string EnterTheCodeBelowToRefreshThePassword {
            get {
                return ResourceManager.GetString("EnterTheCodeBelowToRefreshThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name must be a maximum of 255 characters..
        /// </summary>
        public static string FullNameMaxLength {
            get {
                return ResourceManager.GetString("FullNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name: Must be a minimum of 3 characters..
        /// </summary>
        public static string FullNameMinLength {
            get {
                return ResourceManager.GetString("FullNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name required field..
        /// </summary>
        public static string FullNameReqired {
            get {
                return ResourceManager.GetString("FullNameReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code required field..
        /// </summary>
        public static string LanguageCodeReqired {
            get {
                return ResourceManager.GetString("LanguageCodeReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It should not contain Turkish characters. {0}.
        /// </summary>
        public static string NotTurkishCharacter {
            get {
                return ResourceManager.GetString("NotTurkishCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be a maximum of 32 characters..
        /// </summary>
        public static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be a minimum of 8 characters..
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required field..
        /// </summary>
        public static string PasswordReqired {
            get {
                return ResourceManager.GetString("PasswordReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in sending password..
        /// </summary>
        public static string ThereWasAnErrorInSendingPassword {
            get {
                return ResourceManager.GetString("ThereWasAnErrorInSendingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username must be a maximum of 255 characters..
        /// </summary>
        public static string UserNameMaxLength {
            get {
                return ResourceManager.GetString("UserNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username must be a minimum of 3 characters..
        /// </summary>
        public static string UserNameMinLength {
            get {
                return ResourceManager.GetString("UserNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name required field..
        /// </summary>
        public static string UserNameReqired {
            get {
                return ResourceManager.GetString("UserNameReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have received a request to renew your ContestPark password..
        /// </summary>
        public static string WeHaveReceivedARequestToRenewYourContestParkPassword {
            get {
                return ResourceManager.GetString("WeHaveReceivedARequestToRenewYourContestParkPassword", resourceCulture);
            }
        }
    }
}
