//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestPark.Balance.API.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BalanceResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BalanceResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ContestPark.Balance.API.Resources.BalanceResource", typeof(BalanceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        public static string InvalidPlatformType {
            get {
                return ResourceManager.GetString("InvalidPlatformType", resourceCulture);
            }
        }
        
        public static string PackagenameIsIncorrect {
            get {
                return ResourceManager.GetString("PackagenameIsIncorrect", resourceCulture);
            }
        }
        
        public static string ThePurchaseFailedPleaseEmailWithOurSupportTeam {
            get {
                return ResourceManager.GetString("ThePurchaseFailedPleaseEmailWithOurSupportTeam", resourceCulture);
            }
        }
        
        public static string TheWithdrawalRequestFailed {
            get {
                return ResourceManager.GetString("TheWithdrawalRequestFailed", resourceCulture);
            }
        }
    }
}
