//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestPark.Post.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PostResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContestPark.Post.API.Resources.PostResource", typeof(PostResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding comment failed..
        /// </summary>
        public static string AddingCommentFailed {
            get {
                return ResourceManager.GetString("AddingCommentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during the rating removal..
        /// </summary>
        public static string AnUnexpectedErrorOccurredDuringTheRatingRemoval {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredDuringTheRatingRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already liked this post..
        /// </summary>
        public static string YouAlreadyLikedThisPost {
            get {
                return ResourceManager.GetString("YouAlreadyLikedThisPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to like this post before to remove liking..
        /// </summary>
        public static string YouHaveToLikeThisPostBeforeToRemoveLiking {
            get {
                return ResourceManager.GetString("YouHaveToLikeThisPostBeforeToRemoveLiking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your like process did not happen, please try again..
        /// </summary>
        public static string YourLikeProcessDidNotHappenPleaseTryAgain {
            get {
                return ResourceManager.GetString("YourLikeProcessDidNotHappenPleaseTryAgain", resourceCulture);
            }
        }
    }
}
